version: "3"

services:
  docker-express:
    build: .
    ports:
      - "5500:5500"
    volumes:
      - ./:/code/docker-express
      - /code/docker-express/node_modules
    image: docker-express-image
    container_name: docker-express-container
    env_file:
      - ./.env