version: "3"

services:
  docker-express:
    build: 
      context: .
      args: 
        NODE_ENV: development
    volumes:
      - ./:/code/docker-express
      - /code/docker-express/node_modules
    environment:
      - NODE_ENV=development
    command: npm run dev